---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["private_network", {ip: 192.168.150.4}]
      customize:
        cpus: 2
        memory: 4096

  - name: ubuntu-14.04
    driver_config:
      network:
      - ["private_network", {ip: 192.168.150.4}]
      customize:
        cpus: 2
        memory: 4096

  - name: centos-7.0
    driver_config:
      network:
      - ["private_network", {ip: 192.168.150.4}]
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: default
    run_list:
      - recipe[ghost-blog::default]
    attributes:
